# Generated by Django 3.2.5 on 2021-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('title_description', models.TextField()),
                ('sub_title_description', models.TextField()),
                ('image', models.ImageField(upload_to='services')),
                ('icons', models.ImageField(upload_to='services_icon')),
            ],
        ),
    ]
