# Generated by Django 3.2.5 on 2021-12-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('address', models.TextField(primary_key=True, serialize=False)),
                ('district', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('local_address', models.TextField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.city')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('name', models.TextField(unique=True)),
                ('clinic_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=500)),
                ('website', models.TextField()),
                ('image', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.locality')),
            ],
        ),
    ]
