# Generated by Django 3.2.5 on 2022-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='days_of_treatment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pills_per_day',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription',
            field=models.TextField(blank=True),
        ),
    ]
