# Generated by Django 3.2.5 on 2021-12-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_year', models.DateField()),
                ('registration_no', models.CharField(max_length=200)),
                ('reg_year', models.DateField()),
                ('experience', models.CharField(blank=True, max_length=10)),
                ('registration_verification', models.BooleanField(default=False)),
                ('degree_verification', models.BooleanField(default=False)),
                ('photo_verification', models.BooleanField(default=False)),
                ('final_verification', models.BooleanField(default=False)),
                ('short_bio', models.TextField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('district', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCouncil',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Enter number between 1 to 5')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_rating', to='Doctor.basicinfo')),
            ],
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.degree'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.institution'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='reg_council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.registrationcouncil'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.specialization'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
