# Generated by Django 3.2.5 on 2022-02-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='degree_year',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='reg_year',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='specialization',
            field=models.ForeignKey(default='ENT', on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.specialization'),
        ),
    ]
