# Generated by Django 3.2.5 on 2022-02-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_basicinfo_reg_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='degree_year',
            field=models.DateField(null=True),
        ),
    ]
