# Generated by Django 3.2.5 on 2022-02-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_basicinfo_degree_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.degree'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='experience',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.institution'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reg_council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.registrationcouncil'),
        ),
    ]
